---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyIP:
    Description: CIDR block for VPC defaults to 10.45.0.0
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}'
    ConstraintDescription: Must be an IP address in the form x.x.x.x
    Type: String
    Default: 10.45.0.0

Resources:
  JenkinsServer:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: 'ami-0dc96254d5535925f'
      InstanceType: 't2.micro'
      KeyName: 'BuildServer'
      SecurityGroups: 
        - !Ref InstanceSecurityGroup
      SubnetId: String
      Tags: 
        - 
          Key: 'Name'
          Value: 'Jenkins'
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

