---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyIP:
    Description: My IP address for security group
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: Must be an IP address in the form x.x.x.x
    Type: String

Resources:
  JenkinsServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          commands:
            createFile:
              command: echo MAGIC > test.txt
              cwd: "~"
          files: 
            /tmp/setup.mysql: 
              content: !Sub | 
                CREATE DATABASE test;
                CREATE USER 'dazza'@'localhost' IDENTIFIED BY 'testpwd';
                GRANT ALL ON test.* TO 'dazza'@'localhost';
                FLUSH PRIVILEGES;
              mode: "000644"
              owner: "root"
              group: "root"
    Properties: 
      ImageId: 'ami-0dc96254d5535925f'
      InstanceType: 't2.micro'
      KeyName: 'BuildServer'
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup
      SubnetId: !ImportValue VPC:PublicSubnetCIDR
      Tags: 
        - 
          Key: 'Name'
          Value: 'Jenkins'
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              # Install the files and packages from the metadata
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource JenkinsServer '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Join [ "/", [!Ref MyIP, 32] ]
      VpcId: !ImportValue VPC:BuildVpcID

