---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyIP:
    Description: My IP address for security group
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: Must be an IP address in the form x.x.x.x
    Type: String
  MyDomainName:
    Description: Domain Name (optional)
    Type: String

Conditions:
  AddRoute53:
    !Not
      - !Equals
        - ""
        - !Ref MyDomainName

Resources:
  JenkinsServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              java-1.8.0-openjdk-devel: []
              git: []
              jenkins: []
#          commands:
#            addJenkinsRepo:
#              command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
#            importPublicKey:
#              command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    Properties: 
      ImageId: 'ami-0dc96254d5535925f'
      InstanceType: 't2.micro'
      KeyName: 'BuildServer'
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup
      SubnetId: !ImportValue VPC:PublicSubnetCIDR
      Tags: 
        - 
          Key: 'Name'
          Value: 'Jenkins'
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
              # Update the helper scripts
              yum install -y aws-cfn-bootstrap
              wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
              rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
              # Install the files and packages from the metadata
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource JenkinsServer '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: Jenkins Web Security Group
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Join [ "/", [!Ref MyIP, 32] ]
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: !Join [ "/", [!Ref MyIP, 32] ]
      VpcId: !ImportValue VPC:BuildVpcID

  DnsRecord:
    Type: AWS::Route53::RecordSet
    Condition: AddRoute53
    Properties:
      HostedZoneName: !Join ['', [!Ref 'MyDomainName', .]]
      Comment: DNS name for my instance.
      Name: !Join ['', ['Jenkins', ., !Ref 'MyDomainName']]
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt JenkinsServer.PublicIp



