---
AWSTemplateFormatVersion: 2010-09-09

Description:
  This template creates the VPC and workload as nested stacks.

Parameters:
  MyVpcCIDR:
    Description: CIDR block for VPC defaults to 10.45.0.0
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}'
    ConstraintDescription: Must be an IP address in the form x.x.x.x
    Type: String
    Default: 10.45.0.0
  MyIP:
    Description: My IP address for security group
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: Must be an IP address in the form x.x.x.x
    Type: String
  MyDomainName:
    Description: Domain Name (optional)
    Type: String

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://darrenharris-ap-southeast-2.s3-ap-southeast-2.amazonaws.com/vpc.template.yaml
      Parameters:
        MyVpcCIDR: !Ref MyVpcCIDR

  BuildServer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://darrenharris-ap-southeast-2.s3-ap-southeast-2.amazonaws.com/jenkins.template.yaml
      Parameters:
        MyIP: !Ref MyIP
        MyDomainName: !Ref MyDomainName
